/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.simple.clinic.outpatient.view.registration;

import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.util.function.Consumer;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.simple.clinic.outpatient.MainOutpatientFrame;
import org.simple.clinic.outpatient.model.Patient;
import org.simple.clinic.outpatient.repository.PatientRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author fef339
 */
@Component
public class RegistrationDataPanel extends javax.swing.JPanel {

    private static final Logger logger = 
            LoggerFactory.getLogger(
            RegistrationDataPanel.class);

    private final PatientRepository 
            patientRepository;

    private final RegistrationPanel 
            registrationPanel;

    /**
     * Creates new form RegistrationDataPanel
     *
     * @param patientRepository
     * @param registrationPanel
     */
    public RegistrationDataPanel(
            PatientRepository patientRepository,
            RegistrationPanel registrationPanel) {
        initComponents();
        this.patientRepository = 
                patientRepository;
        this.registrationPanel = 
                registrationPanel;
    }

    public void loadData() {
        List<Patient> patientList = 
                patientRepository.findAll();
        clearDataPatientTable();
        DefaultTableModel model = (
                DefaultTableModel) 
                patientTable.getModel();
        for (int i = 0; i < patientList
                .size(); i++) {
            Patient get = patientList
                    .get(i);
            model.addRow(new Object[]{
                get.getPatientId().toString(),
                get.getPatientName(),
                get.getBirthDate(),
                get.getAddress()
            });
        }
    }

    private void clearDataPatientTable() {
        DefaultTableModel model = (
                DefaultTableModel) 
                patientTable.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        updatePatientBtn = new javax.swing.JButton();
        addPatientBtn = new javax.swing.JButton();

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Name", "Birth Date", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientTable);

        updatePatientBtn.setText("Update Patient");
        updatePatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientBtnActionPerformed(evt);
            }
        });

        addPatientBtn.setText("Add Patient");
        addPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPatientBtn)
                .addGap(18, 18, 18)
                .addComponent(updatePatientBtn)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePatientBtn)
                    .addComponent(addPatientBtn))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showRegistrationPanel() {
        registrationPanel.
                setRegistrationDataPanel(
                        this);
        registrationPanel.clearData();
        JViewport viewport = (JViewport) 
                this.getParent();
        viewport.removeAll();
        viewport.setView(registrationPanel);
    }
    private void addPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBtnActionPerformed
        showRegistrationPanel();
    }//GEN-LAST:event_addPatientBtnActionPerformed

    private void updatePatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientBtnActionPerformed
        DefaultTableModel model = (
                DefaultTableModel) 
                patientTable.getModel();
        int rowSelected = patientTable.
                getSelectedRow();
        String id = (String) model.
                getValueAt(rowSelected, 
                        0);
        logger.info("ID = " + id);
        showRegistrationPanel();
        registrationPanel.loadDataById(
                Integer.parseInt(id));
    }//GEN-LAST:event_updatePatientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientTable;
    private javax.swing.JButton updatePatientBtn;
    // End of variables declaration//GEN-END:variables
}
