/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.simple.clinic.outpatient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;


/**
 *
 * @author fef339
 */
@Component
public class MainOutpatientFrame extends javax.swing.JFrame {
    
    private final LoginFrame loginFrame;
    private static final Logger logger = LoggerFactory.getLogger(MainOutpatientFrame.class);
  
    /**
     * Creates new form MainOutpatientFrame
     * @param loginFrame
     */
    public MainOutpatientFrame(LoginFrame loginFrame) {
        initComponents();
        this.loginFrame = loginFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        applicationMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        logoutMnItm = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));

        fileMenu.setText("File");

        logoutMnItm.setText("Logout");
        logoutMnItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMnItmActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMnItm);

        applicationMenuBar.add(fileMenu);

        editMenu.setText("Edit");
        applicationMenuBar.add(editMenu);

        setJMenuBar(applicationMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMnItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMnItmActionPerformed
        loginFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutMnItmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar applicationMenuBar;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem logoutMnItm;
    // End of variables declaration//GEN-END:variables
}
