/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.simple.clinic.outpatient.view.doctor;

import org.springframework.stereotype.Component;

/**
 *
 * @author fef339
 */
@Component
public class RegistrationDoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationDoctorPanel
     */
    public RegistrationDoctorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorNameLbl = new javax.swing.JLabel();
        doctorNameTxt = new javax.swing.JTextField();
        doctorSpecialistLbl = new javax.swing.JLabel();
        doctorSpecialistTxt = new javax.swing.JTextField();
        doctorRegistrationBtn = new javax.swing.JButton();

        doctorNameLbl.setText("Doctor Name");

        doctorSpecialistLbl.setText("Specialist");

        doctorRegistrationBtn.setText("Register Doctor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorNameLbl)
                    .addComponent(doctorSpecialistLbl))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorRegistrationBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(doctorNameTxt)
                        .addComponent(doctorSpecialistTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorNameLbl)
                    .addComponent(doctorNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorSpecialistLbl)
                    .addComponent(doctorSpecialistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(doctorRegistrationBtn)
                .addContainerGap(615, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doctorNameLbl;
    private javax.swing.JTextField doctorNameTxt;
    private javax.swing.JButton doctorRegistrationBtn;
    private javax.swing.JLabel doctorSpecialistLbl;
    private javax.swing.JTextField doctorSpecialistTxt;
    // End of variables declaration//GEN-END:variables
}
