/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.simple.clinic.outpatient.view.doctor;

import java.util.List;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import org.simple.clinic.outpatient.model.Doctor;
import org.simple.clinic.outpatient.repository.DoctorRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author fef339
 */
@Component
public class RegistrationDoctorDataPanel extends javax.swing.JPanel {
    
    private static final Logger logger = LoggerFactory.getLogger(RegistrationDoctorDataPanel.class);
    
    private final DoctorRepository doctorRepository;
    
    private final RegistrationDoctorPanel registrationDoctorPanel;

    /**
     * Creates new form RegistrationDoctorDataPanel
     * @param doctorRepository
     * @param registrationDoctorPanel
     */
    public RegistrationDoctorDataPanel(DoctorRepository doctorRepository, RegistrationDoctorPanel registrationDoctorPanel) {
        initComponents();
        this.doctorRepository = doctorRepository;
        this.registrationDoctorPanel = registrationDoctorPanel;
    }
    
    private void clearDataDoctorTable(){
        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();
        model.setRowCount(0);
    }
    
    public void loadData() {
        List<Doctor> doctorList = doctorRepository.findAll();
        clearDataDoctorTable();
        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();
        for (int i = 0; i < doctorList.size(); i++) {
            Doctor get = doctorList.get(i);
            model.addRow(new Object[]{
                get.getDoctorId().toString(),
                get.getDoctorName(),
                get.getSpecialist()
            });
        }
    }
    
    private void showRegistrationDoctorPanel() {
        registrationDoctorPanel.setRegistrationDoctorDataPanel(this);
        registrationDoctorPanel.clearData();
        JViewport viewport = (JViewport) 
                this.getParent();
        viewport.removeAll();
        viewport.setView(registrationDoctorPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDoctorBtn = new javax.swing.JButton();
        updateDoctorBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTbl = new javax.swing.JTable();

        addDoctorBtn.setText("Add Doctor");
        addDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorBtnActionPerformed(evt);
            }
        });

        updateDoctorBtn.setText("Update Doctor");
        updateDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorBtnActionPerformed(evt);
            }
        });

        doctorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor Id", "Doctor Name", "Specialist"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(doctorTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDoctorBtn)
                .addGap(49, 49, 49)
                .addComponent(updateDoctorBtn)
                .addGap(35, 35, 35))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDoctorBtn)
                    .addComponent(updateDoctorBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorBtnActionPerformed
        showRegistrationDoctorPanel();
    }//GEN-LAST:event_addDoctorBtnActionPerformed

    private void updateDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoctorBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) doctorTbl.getModel();
        int rowSelected = doctorTbl.getSelectedRow();
        
        String id = (String) model.getValueAt(rowSelected, 0);
        showRegistrationDoctorPanel();
        registrationDoctorPanel.loadDataById(Integer.parseInt(id));
    }//GEN-LAST:event_updateDoctorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorBtn;
    private javax.swing.JTable doctorTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateDoctorBtn;
    // End of variables declaration//GEN-END:variables
}
